variables: 
  - key: "backend_resgrp"
    value: "ffeslz-mgmt"
  - key: "backend_storage_account"
    value: "ffeslzstates"
  - key: "backend_container"
    value: "devtfstate"
  - key: "tf_var_root_name"
    value: "Forefront-Dev"
  - key: "tf_var_root_id"
    value: "forefrdev"
  - key: "tf_var_connectivity_subid"
    value: "01fb43ea-bea4-46fb-8939-fc958fc989e9"
  - key: "tf_var_management_subid"
    value: "72900686-b05e-4829-a2e7-080028c26393"
  - key: "tf_var_identity_subid"
    value: "c34b7eb8-c78e-4f4c-b3b3-22a91c93e52c"
  - key: "arm_client_id"
    value: "127f774b-083c-4d7a-84ea-f0eb8f070cf8"
  - key: "arm_subscription_id"
    value: "14bbbdfe-3992-46e7-9a9e-65aae95e071a"
  - key: "arm_tenant_id"
    value: "dcd5d5df-cb89-42a7-85cc-e3b113d4aad1"
  - key: "tf_var_security_alerts_email_address"
    value: "macowen@microsoft.com"
  - key: "tf_var_corp_subs"
    value: '["e2af51e5-658a-493a-9dec-723132eeeeaf"]'
  - key: "tf_var_sandboxes"
    value: '[]'
  - key: "tf_var_connectivity_resources_location_1"
    value: "uksouth"
  - key: "tf_var_connectivity_resources_location_2"
    value: "ukwest"
  - key: "tf_var_connectivity_subscription_owner"
    value: "admin@cowenmc.onmicrosoft.com"
  - key: "tf_var_identity_subscription_owner"
    value: "admin@cowenmc.onmicrosoft.com"
  - key: "tf_var_management_subscription_owner"
    value: "admin@cowenmc.onmicrosoft.com"
  - key: "tf_var_key_vault_id"
    value: "ff002"
  - key: "tf_var_gateway_fqdn"
    value: "ds.mattcowen.co.uk"
