variables: 
  - key: "backend_resgrp"
    value: "ffeslz-mgmt"
  - key: "backend_storage_account"
    value: "ffeslzstates"
  - key: "backend_container"
    value: "prodtfstate"
  - key: "tf_var_root_name"
    value: "Forefront"
  - key: "tf_var_root_id"
    value: "forefront"
  - key: "tf_var_connectivity_subid"
    value: "89e43216-d6ca-42b0-8920-e5faa1445b1a"
  - key: "tf_var_management_subid"
    value: "691ad1a9-62f9-4f9c-8705-0bd4e9c970de"
  - key: "tf_var_identity_subid"
    value: "e26892a6-fa92-4133-9957-eed416254789"
  - key: "arm_client_id"
    value: "127f774b-083c-4d7a-84ea-f0eb8f070cf8"
  - key: "arm_subscription_id"
    value: "14bbbdfe-3992-46e7-9a9e-65aae95e071a"
  - key: "arm_tenant_id"
    value: "dcd5d5df-cb89-42a7-85cc-e3b113d4aad1"
  - key: "tf_var_security_alerts_email_address"
    value: "macowen@microsoft.com"
  - key: "corp_subs"
    value: '["f82ddacd-1551-479d-9a0f-3c9774583ab6"]'
  - key: "sandboxes"
    value: '[]'
  - key: "tf_var_mgmt_location"
    value: "uksouth"
  - key: "tf_var_connectivity_location"
    value: "uksouth"
