variables: 
  - key: "backend_resgrp"
    value: "ffeslz-mgmt"
  - key: "backend_storage_account"
    value: "ffeslzstates"
  - key: "backend_container"
    value: "testtfstate"
  - key: "tf_var_root_name"
    value: "Forefront-Test"
  - key: "tf_var_root_id"
    value: "forefrtest"
  - key: "tf_var_connectivity_subid"
    value: "19b05369-968e-4679-bcad-e0e27da3b97f"
  - key: "tf_var_management_subid"
    value: "855b99a8-e169-48ec-923e-894828087b8f"
  - key: "tf_var_identity_subid"
    value: "b41c0c04-8748-4a05-bf00-d4125ca4488b"
  - key: "arm_client_id"
    value: "127f774b-083c-4d7a-84ea-f0eb8f070cf8"
  - key: "arm_subscription_id"
    value: "14bbbdfe-3992-46e7-9a9e-65aae95e071a"
  - key: "arm_tenant_id"
    value: "dcd5d5df-cb89-42a7-85cc-e3b113d4aad1"
  - key: "tf_var_security_alerts_email_address"
    value: "macowen@microsoft.com"
  - key: "corp_subs"
    value: '["29e6d720-47b6-4ad2-bf3b-c2f395787af2"]'
  - key: "sandboxes"
    value: '["1f8c2fa4-c573-4cd4-9bfd-5fdd12c0a8c4"]'
  - key: "tf_var_mgmt_location"
    value: "uksouth"
  - key: "tf_var_connectivity_location"
    value: "uksouth"
