variables: 
  - key: "backend-resgrp"
    value: "ffeslz-mgmt"
  - key: "backend-storage-account"
    value: "ffeslzstates"
  - key: "backend-container"
    value: "terraformstate"
  - key: "tf-var-root-name"
    value: "Forefront-Test"
  - key: "tf-var-root-id"
    value: "forefrtest"
  - key: "tf-var-connectivity-subid"
    value: "19b05369-968e-4679-bcad-e0e27da3b97f"
  - key: "tf-var-management-subid"
    value: "855b99a8-e169-48ec-923e-894828087b8f"
  - key: "tf-var-identity-subid"
    value: "b41c0c04-8748-4a05-bf00-d4125ca4488b"
  - key: "arm-client-id"
    value: "127f774b-083c-4d7a-84ea-f0eb8f070cf8"
  - key: "arm-subscription-id"
    value: "14bbbdfe-3992-46e7-9a9e-65aae95e071a"
  - key: "arm-tenant-id"
    value: "dcd5d5df-cb89-42a7-85cc-e3b113d4aad1"
  - key: "tf-var-security-alerts-email-address"
    value: "macowen@microsoft.com"