name: build-agent

on:
  push:
    branches:
      - gareth-local-dev
    paths:
      - build-agent-tools/**
      - .github/workflows/build-agent.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master #TODO test
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - uses: Azure/login@v1
      with:
        creds: '{ "clientId": "${{ secrets.CLIENTID }}", "clientSecret": "${{ secrets.CLIENTSECRET }}", "subscriptionId": "${{ secrets.SUBID }}", "tenantId": "${{ secrets.TENANTID }}" }'

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./build-agent-tools
        push: true
        tags: ffmgmtacr.azurecr.io/build-agent-tools:latest
