name: build-agent

on:
  push:
    branches:
      - main
    paths:
      - build-agent-tools/**
      - .github/workflows/build-agent.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: actions/checkout@master #TODO test
    - name: Create ./build-agent-tools/configuration
      run: |
        mkdir ./build-agent-tools/configuration
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ffmgmtacr.azurecr.io
        username: ${{ secrets.CLIENTID }}
        password: ${{ secrets.CLIENTSECRET }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./build-agent-tools
        push: true
        tags: ffmgmtacr.azurecr.io/build-agent-tools:${{ steps.date.outputs.date }},ffmgmtacr.azurecr.io/build-agent-tools:latest
