name: tenant-deploy-test
on:
  push:
    branches:
      - test
    paths:
      - tenant/**
      - .github/workflows/tenant-deploy-test.yml


env:
  subscriptionId: "0f837e64-c72f-4d8f-9d5b-28cd9bc3674d"
  tenantId: "dcd5d5df-cb89-42a7-85cc-e3b113d4aad1"
  parentId: "envsmgmt"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: ffmgmtacr.azurecr.io/build-agent-tools:latest
      credentials:
        username: ${{ secrets.CLIENTID }}
        password: ${{ secrets.CLIENTSECRET }}
    steps:
    
    - name: work around permission issue
      run: git config --global --add safe.directory /__w/forefront-lz/forefront-lz
    
    - uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_TEST_CREDENTIALS }}

    - name: Retrieve secrets from key vault
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: 'ffmgmtkv'
        secrets: 'arm-client-secret'
      id: getSecrets
    
    - name: Retrieve variables from test-variables.yml
      uses: lindluni/actions-variable-groups@v1.0.1
      with:
        org: mattcowen
        repo: forefront-lz
        groups: |
          .github/test-variables.yml
      id: getVars

    - name: Print Environment
      run: env | sort

    - name: Print tooling versions
      run: |
        terraform --version
        az --version

    - name: Terraform Init     
      env:
        BACKEND_RESGRP: ${{ steps.getVars.outputs.backend_resgrp }}
        BACKEND_STORAGE_ACCOUNT: ${{ steps.getVars.outputs.backend_storage_account }}
        BACKEND_CONTAINER: ${{ steps.getVars.outputs.backend_container }}
        BACKEND_CLIENT_ID: ${{ secrets.CLIENTID }}
        BACKEND_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
        BACKEND_CLIENT_SUBSCRIPTION_ID: $subscriptionId
        BACKEND_CLIENT_TENANTID: $tenantId
        ARM_CLIENT_ID: ${{ steps.getVars.outputs.arm_client_id }}
        ARM_CLIENT_SECRET: ${{ steps.getSecrets.outputs.arm_client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ steps.getVars.outputs.arm_subscription_id }}
        ARM_TENANT_ID: ${{ steps.getVars.outputs.arm_tenant_id }}
      run: |
        cd tenant
        bash terraform-init.sh

    - name: Terraform Plan Before
      env:
        BACKEND_RESGRP: ${{ steps.getVars.outputs.backend_resgrp }}
        BACKEND_STORAGE_ACCOUNT: ${{ steps.getVars.outputs.backend_storage_account }}
        BACKEND_CONTAINER: ${{ steps.getVars.outputs.backend_container }}
        BACKEND_CLIENT_ID: ${{ secrets.CLIENTID }}
        BACKEND_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
        BACKEND_CLIENT_SUBSCRIPTION_ID: $subscriptionId
        BACKEND_CLIENT_TENANTID: $tenantId
        ARM_CLIENT_ID: ${{ steps.getVars.outputs.arm_client_id }}
        ARM_CLIENT_SECRET: ${{ steps.getSecrets.outputs.arm_client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ steps.getVars.outputs.arm_subscription_id }}
        ARM_TENANT_ID: ${{ steps.getVars.outputs.arm_tenant_id }}

        TF_VAR_parent_id: $parentId
        TF_VAR_root_name: $tf_var_root_name
        TF_VAR_root_id: $tf_var_root_id
        TF_VAR_connectivity_subid: $tf_var_connectivity_subid
        TF_VAR_management_subid: $tf_var_management_subid
        TF_VAR_identity_subid: $tf_var_identity_subid
        TF_VAR_corp_subs: $corp_subs
        TF_VAR_sandboxes: $sandboxes

        TF_VAR_security_alerts_email_address: $tf_var_security_alerts_email_address
        TF_VAR_management_resources_location: $tf_var_mgmt_location
        TF_VAR_connectivity_resources_location: $tf_var_connectivity_location

        TF_VAR_running_ci_pipeline: "true"
        TF_IN_AUTOMATION: "true"
      run: |
        cd tenant
        terraform-plan-before.sh testplan
 