name: tenant-deploy-test
on:
  pull_request:
    branches:
      - test
    paths:
      - tenant/**
      - .github/workflows/tenant-deploy-test.yml

defaults:
  subscriptionId: "0f837e64-c72f-4d8f-9d5b-28cd9bc3674d"
  tenantId: "dcd5d5df-cb89-42a7-85cc-e3b113d4aad1"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: ffmgmtacr.azurecr.io/build-agent-tools:latest
      credentials:
        username: ${{ secrets.CLIENTID }}
        password: ${{ secrets.CLIENTSECRET }}
    steps:
      
    - uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: '{ "clientId": "${{ secrets.CLIENTID }}", "clientSecret": "${{ secrets.CLIENTSECRET }}", "subscriptionId": "${subscriptionId}", "tenantId": "${tenantId}" }'

    - name: Retrieve secrets from key vault
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: 'ffmgmtkv'
        secrets: 'arm-client-secret'
      id: getSecrets
    
    - name: Retrieve variables from test-variables.yml
      uses: lindluni/actions-variable-groups@v1.0.1
      with:
        org: mattcowen
        repo: forefront-lz
        groups: |
          .github/test-variables.yml
      id: getVars

    - name: Print Environment
      run: env | sort

    - name: Print tooling versions
      run: |
        terraform --version
        az --version

    - name: Terraform Init     
      env:
        BACKEND_RESGRP: ${{ steps.getVars.outputs.backend-resgrp }}
        BACKEND_STORAGE_ACCOUNT: ${{ steps.getVars.outputs.backend-storage-account }}
        BACKEND_CONTAINER: ${{ steps.getVars.outputs.backend-container }}
        BACKEND_CLIENT_ID: ${{ secrets.CLIENTID }}
        BACKEND_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
        BACKEND_CLIENT_SUBSCRIPTION_ID: ${subscriptionId}
        BACKEND_CLIENT_TENANTID: ${tenantId}
        ARM_CLIENT_ID: ${{ steps.getVars.outputs.arm-client-id }}
        ARM_CLIENT_SECRET: ${{ steps.getSecrets.outputs.arm-client-secret }}
        ARM_SUBSCRIPTION_ID: ${{ steps.getVars.outputs.arm-subscription-id }}
        ARM_TENANT_ID: ${{ steps.getVars.outputs.arm-tenant-id }}
      run: |
        cd tenant
        bash terraform-init.sh

 
