name: tenant-deploy-test
on:
  push:
    branches:
      - test
    paths:
      - tenant/**
      - .github/workflows/tenant-deploy-test.yml

env:
  subscriptionId: "0f837e64-c72f-4d8f-9d5b-28cd9bc3674d"
  tenantId: "dcd5d5df-cb89-42a7-85cc-e3b113d4aad1"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: ffmgmtacr.azurecr.io/build-agent-tools:latest
      credentials:
        username: ${{ secrets.CLIENTID }}
        password: ${{ secrets.CLIENTSECRET }}
    steps:
      
    - uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_TEST_CREDENTIALS }}

    - name: Retrieve secrets from key vault
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: 'ffmgmtkv'
        secrets: 'arm-client-secret'
      id: getSecrets
    
    - name: Retrieve variables from test-variables.yml
      uses: lindluni/actions-variable-groups@v1.0.1
      with:
        org: mattcowen
        repo: forefront-lz
        groups: |
          .github/test-variables.yml
      id: getVars

    - name: Print Environment
      run: env | sort

    - name: Print tooling versions
      run: |
        terraform --version
        az --version

    - name: Terraform Init     
      env:
        BACKEND_RESGRP: ${{ steps.getVars.outputs.backend-resgrp }}
        BACKEND_STORAGE_ACCOUNT: ${{ steps.getVars.outputs.backend-storage-account }}
        BACKEND_CONTAINER: ${{ steps.getVars.outputs.backend-container }}
        BACKEND_CLIENT_ID: ${{ secrets.CLIENTID }}
        BACKEND_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
        BACKEND_CLIENT_SUBSCRIPTION_ID: $subscriptionId
        BACKEND_CLIENT_TENANTID: $tenantId
        ARM_CLIENT_ID: ${{ steps.getVars.outputs.arm-client-id }}
        ARM_CLIENT_SECRET: ${{ steps.getSecrets.outputs.arm-client-secret }}
        ARM_SUBSCRIPTION_ID: ${{ steps.getVars.outputs.arm-subscription-id }}
        ARM_TENANT_ID: ${{ steps.getVars.outputs.arm-tenant-id }}
      run: |
        cd tenant
        bash terraform-init.sh

 
    - name: Terraform Plan Before
      env:
        BACKEND_RESGRP: ${{ steps.getVars.outputs.backend-resgrp }}
        BACKEND_STORAGE_ACCOUNT: ${{ steps.getVars.outputs.backend-storage-account }}
        BACKEND_CONTAINER: ${{ steps.getVars.outputs.backend-container }}
        BACKEND_CLIENT_ID: ${{ secrets.CLIENTID }}
        BACKEND_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
        BACKEND_CLIENT_SUBSCRIPTION_ID: $subscriptionId
        BACKEND_CLIENT_TENANTID: $tenantId
        ARM_CLIENT_ID: ${{ steps.getVars.outputs.arm-client-id }}
        ARM_CLIENT_SECRET: ${{ steps.getSecrets.outputs.arm-client-secret }}
        ARM_SUBSCRIPTION_ID: ${{ steps.getVars.outputs.arm-subscription-id }}
        ARM_TENANT_ID: ${{ steps.getVars.outputs.arm-tenant-id }}

        TF_VAR_parent_id: $tenantId
        TF_VAR_root_name: ${{ steps.getVars.outputs.tf-var-root-name }}
        TF_VAR_root_id: ${{ steps.getVars.outputs.tf-var-root-id }}
        TF_VAR_connectivity_subid: ${{ steps.getVars.outputs.tf-var-connectivity-subid }}
        TF_VAR_management_subid: ${{ steps.getVars.outputs.tf-var-management-subid }}
        TF_VAR_identity_subid: ${{ steps.getVars.outputs.tf-var-identity-subid  }}
        TF_VAR_corp_subs: ${{ steps.getVars.outputs.corp_subs  }}
        TF_VAR_sandboxes: ${{ steps.getVars.outputs.sandboxes  }}

        TF_VAR_security_alerts_email_address: ${{ steps.getVars.outputs.tf-var-security-alerts-email-address }}
        TF_VAR_management_resources_location: ${{ steps.getVars.outputs.tf-var-mgmt-location }}
        TF_VAR_connectivity_resources_location: ${{ steps.getVars.outputs.tf-var-connectivity-location }}

        TF_VAR_running_ci_pipeline: "true"
        TF_IN_AUTOMATION: "true"
      run: |
        cd tenant
        terraform-plan-before.sh testplan

    - name: Terraform Apply
      env:
        BACKEND_RESGRP: ${{ steps.getVars.outputs.backend-resgrp }}
        BACKEND_STORAGE_ACCOUNT: ${{ steps.getVars.outputs.backend-storage-account }}
        BACKEND_CONTAINER: ${{ steps.getVars.outputs.backend-container }}
        BACKEND_CLIENT_ID: ${{ secrets.CLIENTID }}
        BACKEND_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
        BACKEND_CLIENT_SUBSCRIPTION_ID: $subscriptionId
        BACKEND_CLIENT_TENANTID: $tenantId
        ARM_CLIENT_ID: ${{ steps.getVars.outputs.arm-client-id }}
        ARM_CLIENT_SECRET: ${{ steps.getSecrets.outputs.arm-client-secret }}
        ARM_SUBSCRIPTION_ID: ${{ steps.getVars.outputs.arm-subscription-id }}
        ARM_TENANT_ID: ${{ steps.getVars.outputs.arm-tenant-id }}

        TF_VAR_parent_id: $tenantId
        TF_VAR_root_name: ${{ steps.getVars.outputs.tf-var-root-name }}
        TF_VAR_root_id: ${{ steps.getVars.outputs.tf-var-root-id }}
        TF_VAR_connectivity_subid: ${{ steps.getVars.outputs.tf-var-connectivity-subid }}
        TF_VAR_management_subid: ${{ steps.getVars.outputs.tf-var-management-subid }}
        TF_VAR_identity_subid: ${{ steps.getVars.outputs.tf-var-identity-subid  }}
        TF_VAR_corp_subs: ${{ steps.getVars.outputs.corp_subs  }}
        TF_VAR_sandboxes: ${{ steps.getVars.outputs.sandboxes  }}

        TF_VAR_security_alerts_email_address: ${{ steps.getVars.outputs.tf-var-security-alerts-email-address }}
        TF_VAR_management_resources_location: ${{ steps.getVars.outputs.tf-var-mgmt-location }}
        TF_VAR_connectivity_resources_location: ${{ steps.getVars.outputs.tf-var-connectivity-location }}

        TF_VAR_running_ci_pipeline: "true"
        TF_IN_AUTOMATION: "true"
      run: |
        cd tenant
        terraform-apply.sh testplan

    - name: Terraform Plan After
      env:
        BACKEND_RESGRP: ${{ steps.getVars.outputs.backend-resgrp }}
        BACKEND_STORAGE_ACCOUNT: ${{ steps.getVars.outputs.backend-storage-account }}
        BACKEND_CONTAINER: ${{ steps.getVars.outputs.backend-container }}
        BACKEND_CLIENT_ID: ${{ secrets.CLIENTID }}
        BACKEND_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
        BACKEND_CLIENT_SUBSCRIPTION_ID: $subscriptionId
        BACKEND_CLIENT_TENANTID: $tenantId
        ARM_CLIENT_ID: ${{ steps.getVars.outputs.arm-client-id }}
        ARM_CLIENT_SECRET: ${{ steps.getSecrets.outputs.arm-client-secret }}
        ARM_SUBSCRIPTION_ID: ${{ steps.getVars.outputs.arm-subscription-id }}
        ARM_TENANT_ID: ${{ steps.getVars.outputs.arm-tenant-id }}

        TF_VAR_parent_id: $tenantId
        TF_VAR_root_name: ${{ steps.getVars.outputs.tf-var-root-name }}
        TF_VAR_root_id: ${{ steps.getVars.outputs.tf-var-root-id }}
        TF_VAR_connectivity_subid: ${{ steps.getVars.outputs.tf-var-connectivity-subid }}
        TF_VAR_management_subid: ${{ steps.getVars.outputs.tf-var-management-subid }}
        TF_VAR_identity_subid: ${{ steps.getVars.outputs.tf-var-identity-subid  }}
        TF_VAR_corp_subs: ${{ steps.getVars.outputs.corp_subs  }}
        TF_VAR_sandboxes: ${{ steps.getVars.outputs.sandboxes  }}

        TF_VAR_security_alerts_email_address: ${{ steps.getVars.outputs.tf-var-security-alerts-email-address }}
        TF_VAR_management_resources_location: ${{ steps.getVars.outputs.tf-var-mgmt-location }}
        TF_VAR_connectivity_resources_location: ${{ steps.getVars.outputs.tf-var-connectivity-location }}

        TF_VAR_running_ci_pipeline: "true"
        TF_IN_AUTOMATION: "true"
      run: |
        cd tenant
        terraform-plan-after.sh testplan

    - name: Terraform Destroy
      env:
        BACKEND_RESGRP: ${{ steps.getVars.outputs.backend-resgrp }}
        BACKEND_STORAGE_ACCOUNT: ${{ steps.getVars.outputs.backend-storage-account }}
        BACKEND_CONTAINER: ${{ steps.getVars.outputs.backend-container }}
        BACKEND_CLIENT_ID: ${{ secrets.CLIENTID }}
        BACKEND_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
        BACKEND_CLIENT_SUBSCRIPTION_ID: $subscriptionId
        BACKEND_CLIENT_TENANTID: $tenantId
        ARM_CLIENT_ID: ${{ steps.getVars.outputs.arm-client-id }}
        ARM_CLIENT_SECRET: ${{ steps.getSecrets.outputs.arm-client-secret }}
        ARM_SUBSCRIPTION_ID: ${{ steps.getVars.outputs.arm-subscription-id }}
        ARM_TENANT_ID: ${{ steps.getVars.outputs.arm-tenant-id }}

        TF_VAR_parent_id: $tenantId
        TF_VAR_root_name: ${{ steps.getVars.outputs.tf-var-root-name }}
        TF_VAR_root_id: ${{ steps.getVars.outputs.tf-var-root-id }}
        TF_VAR_connectivity_subid: ${{ steps.getVars.outputs.tf-var-connectivity-subid }}
        TF_VAR_management_subid: ${{ steps.getVars.outputs.tf-var-management-subid }}
        TF_VAR_identity_subid: ${{ steps.getVars.outputs.tf-var-identity-subid  }}
        TF_VAR_corp_subs: ${{ steps.getVars.outputs.corp_subs  }}
        TF_VAR_sandboxes: ${{ steps.getVars.outputs.sandboxes  }}

        TF_VAR_security_alerts_email_address: ${{ steps.getVars.outputs.tf-var-security-alerts-email-address }}
        TF_VAR_management_resources_location: ${{ steps.getVars.outputs.tf-var-mgmt-location }}
        TF_VAR_connectivity_resources_location: ${{ steps.getVars.outputs.tf-var-connectivity-location }}

        TF_VAR_running_ci_pipeline: "true"
        TF_IN_AUTOMATION: "true"

      run: |
        cd tenant
        terraform-destroy.sh
